// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_z4ioxjm-_YAncGW_RSagPDaSKAEjors',
    appId: '1:913722725673:ios:577b77500efe937d201338',
    messagingSenderId: '913722725673',
    projectId: 'sys-analysis-4d374',
    storageBucket: 'sys-analysis-4d374.firebasestorage.app',
    iosClientId: '913722725673-1qsvufq1e7jo8tlhun0it78r1mhjosur.apps.googleusercontent.com',
    iosBundleId: 'com.example.sysApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_z4ioxjm-_YAncGW_RSagPDaSKAEjors',
    appId: '1:913722725673:ios:577b77500efe937d201338',
    messagingSenderId: '913722725673',
    projectId: 'sys-analysis-4d374',
    storageBucket: 'sys-analysis-4d374.firebasestorage.app',
    iosClientId: '913722725673-1qsvufq1e7jo8tlhun0it78r1mhjosur.apps.googleusercontent.com',
    iosBundleId: 'com.example.sysApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAxpjK5PUc6SgTVstO_YA8atFSb6wAixY',
    appId: '1:913722725673:web:2305400ad635b9db201338',
    messagingSenderId: '913722725673',
    projectId: 'sys-analysis-4d374',
    authDomain: 'sys-analysis-4d374.firebaseapp.com',
    storageBucket: 'sys-analysis-4d374.firebasestorage.app',
    measurementId: 'G-GVJ2QBWTQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC38BTTEu27-CLmcuw0D8i5xFhQhaphy8c',
    appId: '1:913722725673:android:e04208c941dbcf6e201338',
    messagingSenderId: '913722725673',
    projectId: 'sys-analysis-4d374',
    storageBucket: 'sys-analysis-4d374.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAxpjK5PUc6SgTVstO_YA8atFSb6wAixY',
    appId: '1:913722725673:web:8376406fced122e9201338',
    messagingSenderId: '913722725673',
    projectId: 'sys-analysis-4d374',
    authDomain: 'sys-analysis-4d374.firebaseapp.com',
    storageBucket: 'sys-analysis-4d374.firebasestorage.app',
    measurementId: 'G-Q047SFE1WN',
  );

}